Bumped version to 3.4.1 Updated libs Added more tests regarding the version to the CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -71,6 +71,13 @@ jobs:
           exit 1
         shell: bash
 
+      - name: Test for correct git tag
+        if: github.ref_type == 'tag' && github.ref_name !=  steps.extract_sch_revision.outputs.value
+        run: |
+          echo "::error::Revision number of the schematic/PCB (${{ steps.extract_sch_revision.outputs.value }}) does not match the Github tag (${{ github.ref_name }})."
+          exit 1
+        shell: bash
+
   ERC:
     name: Run ERC
     runs-on: ubuntu-latest
@@ -91,7 +98,7 @@ jobs:
           skip: run_drc
           targets: __NONE__  # Only run preflights
 
-      - name: Retrieve results
+      - name: Upload results
         uses: actions/upload-artifact@v4
         with:
           name: ERC_Output
@@ -117,7 +124,7 @@ jobs:
           skip: run_erc
           targets: __NONE__  # Only run preflights
 
-      - name: Retrieve results
+      - name: Upload results
         uses: actions/upload-artifact@v4
         with:
           name: DRC_Output
@@ -148,19 +155,19 @@ jobs:
       - name: Upload bill of materials files as artifact
         uses: actions/upload-artifact@v4
         with:
-          name: bom-${{ matrix.variant }}
+          name: manufacturing_files-bom-${{ matrix.variant }}
           path: bom_files_compressed
 
       - name: Upload schematic files as artifact
         uses: actions/upload-artifact@v4
         with:
-          name: schematics-${{ matrix.variant }}
+          name: manufacturing_files-schematics-${{ matrix.variant }}
           path: schematics
 
-      - name: Upload schematic files as artifact
+      - name: Upload Gerber files as artifact
         uses: actions/upload-artifact@v4
         with:
-          name: gerber_files-${{ matrix.variant }}
+          name: manufacturing_files-gerber-${{ matrix.variant }}
           path: gerber_files_compressed
 
   release:
@@ -175,13 +182,9 @@ jobs:
       - name: Download manufacturing files artifact
         uses: actions/download-artifact@v4
         with:
-          path: artifacts
-
-      - name: Merge artifacts
-        run: |
-          mkdir ./manufacturing_files
-          mv artifacts/*/* ./manufacturing_files
-        shell: bash
+          path: manufacturing_files
+          pattern: manufacturing_files-*
+          merge-multiple: true
 
       - name: Display structure of downloaded files
         run: ls -R
@@ -191,7 +194,7 @@ jobs:
       - name: Append BOM (bill of materials) as asset
         if: github.event.action == 'published'
         run: |
-          mv "./manufacturing_files/bom/bom_(${{ matrix.variant }}).zip" ${{ needs.tests.outputs.basename }}_bom_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.zip
+          mv "./manufacturing_files/bom_(${{ matrix.variant }}).zip" ${{ needs.tests.outputs.basename }}_bom_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.zip
           gh release upload ${{ github.ref_name }} ${{ needs.tests.outputs.basename }}_bom_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.zip#"Bill of materials for the ${{ matrix.variant }} variant (zip)" --repo ${{ github.repository }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -200,7 +203,7 @@ jobs:
       - name: Append schematics as asset
         if: github.event.action == 'published'
         run: |
-          mv "./manufacturing_files/schematics/schematics_(${{ matrix.variant }}).pdf" ${{ needs.tests.outputs.basename }}_schematics_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.pdf
+          mv "./manufacturing_files/$(basename ${{ env.SCHEMATIC_FILE }} .kicad_sch)_schematics_${{ needs.tests.outputs.revision }}_(${{ matrix.variant }}).pdf" ${{ needs.tests.outputs.basename }}_schematics_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.pdf
           gh release upload ${{ github.ref_name }} ${{ needs.tests.outputs.basename }}_schematics_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.pdf#"Schematics for the ${{ matrix.variant }} variant (pdf)" --repo ${{ github.repository }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -209,7 +212,7 @@ jobs:
       - name: Append position files as asset
         if: github.event.action == 'published'
         run: |
-          mv "./manufacturing_files/gerber_files/pos_(${{ matrix.variant }}).zip" ${{ needs.tests.outputs.basename }}_position_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.zip
+          mv "./manufacturing_files/pos_(${{ matrix.variant }}).zip" ${{ needs.tests.outputs.basename }}_position_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.zip
           gh release upload ${{ github.ref_name }} ${{ needs.tests.outputs.basename }}_position_${{ needs.tests.outputs.revision }}_${{ matrix.variant }}.zip#"Pick & Place position files for the ${{ matrix.variant }} variant (zip)" --repo ${{ github.repository }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -218,7 +221,7 @@ jobs:
       - name: Append Gerber files as asset
         if: github.event.action == 'published' && matrix.variant == 'default'
         run: |
-          mv "./manufacturing_files/gerber_files/gerbers.zip" ${{ needs.tests.outputs.basename }}_gerber_${{ needs.tests.outputs.revision }}_all.zip
+          mv "./manufacturing_files/gerbers_(${{ matrix.variant }}).zip" ${{ needs.tests.outputs.basename }}_gerber_${{ needs.tests.outputs.revision }}_all.zip
           gh release upload ${{ github.ref_name }} ${{ needs.tests.outputs.basename }}_gerber_${{ needs.tests.outputs.revision }}_all.zip#"Gerber files for all variants (zip)" --repo ${{ github.repository }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
